site_name: WindowsSpyBlocker
site_description: Block spying and tracking on Windows
site_author: CrazyMax
site_url: https://crazymax.dev/WindowsSpyBlocker/
edit_uri: edit/master/docs/
docs_dir: docs

repo_name: crazy-max/WindowsSpyBlocker
repo_url: https://github.com/crazy-max/WindowsSpyBlocker

extra:
  seo:
    google: Kscpetr5E2zNDM0pqz-0xhtPZ77oY2oAS6Lid6yEUUM
    bing: D188E0BEC1AB6E7C1E0194BFC35D0033
    #alexa:
    #yandex:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/crazy-max/WindowsSpyBlocker
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/crazyws
  plausible:
    server: plausible.re4per.com
    domain: crazymax.dev/windowsspyblocker

theme:
  name: material
  custom_dir: docs/_overrides
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  include_search_page: false
  search_index_only: true

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - markdown_include.include:
      base_path: docs
  - meta
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - exclude:
      glob:
        - "_overrides/*"
        - ".dockerignore"
        - "Dockerfile"
  - git-revision-date-localized:
      type: iso_datetime
      enable_creation_date: true
  - macros
  - search:
      prebuild_index: python
      lang:
        - en

nav:
  - Home: index.md
  - Usage: usage.md
  - Download: download.md
  - Application:
    - Overview: app/index.md
    - Telemetry:
      - Overview: app/telemetry/index.md
      - Firewall: app/telemetry/firewall.md
      - NCSI: app/telemetry/ncsi.md
    - Dev:
      - Overview: app/dev/index.md
      - Proxifier: app/dev/proxifier.md
      - Sysmon: app/dev/sysmon.md
      - Wireshark: app/dev/wireshark.md
  - Blocking rules:
    - Overview: blocking-rules/index.md
    - Firewall: blocking-rules/firewall.md
    - Hosts: blocking-rules/hosts.md
    - DNSCrypt: blocking-rules/dnscrypt.md
    - ESET Firewall: blocking-rules/eset.md
    - Kaspersky Firewall: blocking-rules/kaspersky.md
    - OpenWrt: blocking-rules/openwrt.md
    - P2P: blocking-rules/p2p.md
    - Proxifier: blocking-rules/proxifier.md
    - simplewall: blocking-rules/simplewall.md
  - FAQ: faq.md
  - Telemetry info: telemetry-info.md
  - Changelog: changelog.md
  - Reporting an issue: reporting-issue.md
  - Contributing: contributing.md
  - Donate: donate.md
